blablabla

In [1]:
import sys
sys.path.append('..') #to find local models as src or config

'''Self modules'''
from src.data_loader import load_data
from src.preprocessing import preprocess
from config import FEATURE_SETS, FEATURE_CONFIG

In [ ]:
df_raw = load_data()

df_clean = preprocess(
    df_raw=df_raw,
    feature_set=FEATURE_SETS["final"],
    feature_config=FEATURE_CONFIG
)

Cache found - loading data from: C:\Users\rapha\.kiro\projects\Predicting-American-Football-Plays\data\cache\pbp_raw.parquet

================================================================================
                              PREPROCESSING REPORT
================================================================================

INPUT:
   Shape: (385991, 372)
   Missing: 52067114 NaNs (36.26%)

OUTPUT:
   Shape: (275135, 29)
   Features (X): 28 columns
   Target (y): 275135 samples
   Missing: 0 NaNs

SELECTED FEATURES IMPUTATION DETAILS:
   Feature Name                   | NaNs Before  | NaNs After  | Filled
   ----------------------------------------------------------------------
   surface                        | 0            | 0           | 0        | -
   season                         | 0            | 0           | 0        | -
   week                           | 0            | 0           | 0        | -
   roof                           | 0            | 0           | 0        | -
   location                       | 0            | 0           | 0        | -
   div_game                       | 0            | 0           | 0        | -
   spread_line                    | 0            | 0           | 0        | -
   goal_to_go                     | 0            | 0           | 0        | -
   game_seconds_remaining         | 0            | 0           | 0        | -
   defteam_timeouts_remaining     | 0            | 0           | 0        | -
   yardline_100                   | 0            | 0           | 0        | -
   total_line                     | 0            | 0           | 0        | -
   wp                             | 0            | 0           | 0        | -
   shotgun                        | 0            | 0           | 0        | -
   down                           | 995          | 0           | 995      | 2.0 (median)
   score_differential             | 0            | 0           | 0        | -
   ydstogo                        | 0            | 0           | 0        | -
   posteam_timeouts_remaining     | 0            | 0           | 0        | -
   quarter_seconds_remaining      | 0            | 0           | 0        | -
   no_huddle                      | 0            | 0           | 0        | -

TARGET DISTRIBUTION:
   1 = PASS: 161,921 (58.9%)
   0 = RUN:  113,214 (41.1%)

================================================================================

In [3]:
df_clean.describe()

,season,week,div_game,spread_line,goal_to_go,game_seconds_remaining,defteam_timeouts_remaining,yardline_100,total_line,wp,...,surface_fieldturf,surface_grass,surface_grass,surface_matrixturf,surface_sportturf,roof_dome,roof_open,roof_outdoors,location_Neutral,target
count,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,...,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000,275135.000000
mean,2019.555313,9.648998,0.355745,1.898953,0.059934,1735.041667,2.621996,51.105421,45.497574,0.500716,...,0.238501,0.524379,0.042143,0.054984,0.052999,0.146408,0.022098,0.701096,0.019423,0.588515
std,2.297545,5.432208,0.478739,6.085511,0.237365,1047.217495,0.672386,24.451376,4.504094,0.295497,...,0.426168,0.499406,0.200916,0.227949,0.224033,0.353516,0.147003,0.457779,0.138007,0.492104
min,2016.000000,1.000000,0.000000,-18.000000,0.000000,0.000000,0.000000,1.000000,28.500000,0.000031,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2018.000000,5.000000,0.000000,-3.000000,0.000000,820.000000,2.000000,32.000000,42.500000,0.261212,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.000000,10.000000,0.000000,3.000000,0.000000,1800.000000,3.000000,55.000000,45.500000,0.514396,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,2022.000000,14.000000,1.000000,6.000000,0.000000,2623.000000,3.000000,72.000000,48.500000,0.736539,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,2023.000000,22.000000,1.000000,22.000000,1.000000,3600.000000,3.000000,99.000000,63.500000,0.999960,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [4]:
df_clean.head(10)

,season,week,div_game,spread_line,goal_to_go,game_seconds_remaining,defteam_timeouts_remaining,yardline_100,total_line,wp,...,surface_fieldturf,surface_grass,surface_grass,surface_matrixturf,surface_sportturf,roof_dome,roof_open,roof_outdoors,location_Neutral,target
0,2016,1,0,3.0,0,3597.0,3.0,86.0,44.5,0.536378,...,0,1,0,0,0,0,0,1,0,0
1,2016,1,0,3.0,0,3572.0,3.0,80.0,44.5,0.541975,...,0,1,0,0,0,0,0,1,0,1
2,2016,1,0,3.0,0,3541.0,3.0,75.0,44.5,0.546262,...,0,1,0,0,0,0,0,1,0,0
3,2016,1,0,3.0,0,3515.0,3.0,75.0,44.5,0.528030,...,0,1,0,0,0,0,0,1,0,1
4,2016,1,0,3.0,0,3474.0,3.0,66.0,44.5,0.561710,...,0,1,0,0,0,0,0,1,0,0
5,2016,1,0,3.0,0,3404.0,3.0,68.0,44.5,0.507005,...,0,1,0,0,0,0,0,1,0,1
6,2016,1,0,3.0,0,3362.0,3.0,66.0,44.5,0.500466,...,0,1,0,0,0,0,0,1,0,0
7,2016,1,0,3.0,0,3315.0,3.0,72.0,44.5,0.447803,...,0,1,0,0,0,0,0,1,0,1
8,2016,1,0,3.0,0,3273.0,3.0,66.0,44.5,0.566390,...,0,1,0,0,0,0,0,1,0,1
9,2016,1,0,3.0,0,3245.0,3.0,63.0,44.5,0.559212,...,0,1,0,0,0,0,0,1,0,1